require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 80

Metrics/MethodLength:
  Max: 15

Naming/VariableNumber:
  Enabled: false

# RSpec Cop Configuration

Metrics/BlockLength:
  AllowedMethods:
    - RSpec.describe
    - before
    - context

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/FilePath:
  SpecSuffixOnly: true
